import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "@/context";
import { cn } from "@/lib/utils";
import Header from "@/components/header";
import SidebarNav from "@/components/sidebar-nav";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={cn("min-h-screen bg-background font-sans antialiased", inter.className)}>
          <Header />
          <main className="flex flex-col md:flex-row">
            <SidebarNav />
            {children}
          </main>
        </body>
      </Providers>
    </html>
  );
}
